### ISSUE TITLE
No iOS parallax support

### ISSUE THREAD

**Issue by orta** [jalxob/cool-kitten#9]
Tested the homepage on an ipad, it looks nice, but doesn't apple parallax.

**Comment by jalxob** [comment]
Parallax effect does not work pretty well on tablets and mobiles. This is just a little step to make it look better :)

**Comment by SevenBits** [comment]
Yes, it looks quite terrible on the iPad.

**Comment by jalxob** [comment]
C'mon guys. It doesn't look bad at all.

**Comment by orta** [comment]
I ended up ditching the parallax for iOS on a prototype of a page I was messing with this weekend [based on cool kitten](http://ortastuff.s3.amazonaws.com/2013/index.html)

You can't do it right because there are no scroll events in iOS, you have to replace the entire scrolling yourself with iScroll which is not an acceptable trade off to me.

**Comment by SevenBits** [comment]
No, it doesn't. But it could be better. That's all we're saying.

**Comment by jalxob** [comment]
Thanks for the feedback, guys.@orta you made a cool work there with Cool Kitten.

**Comment by markdalgleish** [comment]
As @orta mentioned, this is possible when using a scrolling library to emulate native scrolling with CSS transforms.

I wrote an article on my blog describing how to set up Stellar.js with iScroll: http://markdalgleish.com/2012/10/mobile-parallax-with-stellar-js/

**Comment by orta** [comment]
Think @markdalgleish's answer is a nice summary. FWIW I htink someone told me iOS8 did scroll events.
